= ISO 24229 Registry Website

== Introduction

This is the official repository for the ISO 24229 Registry public website.

The site is managed by Ribose Inc.

== Sites

[cols="a,a,a",options="header"]
|===
|Site | Git branch | Deployment URL

|Production | `main`  | https://www.iso24229.org
|Staging    | `staging` | https://staging.iso24229.org

|===

All sites are automatically deployed from their respective branches.

== Usage

=== Prerequisites

- pnpm
  - https://pnpm.io/

=== Project Structure

Inside of your Astro project, you'll see the following folders and files:

[,text]
----
/
├── public/
│   └── favicon.svg
├── src/
│   ├── components/
│   │   └── Card.astro
│   ├── layouts/
│   │   └── Layout.astro
│   └── pages/
│       └── index.astro
└── package.json
----

Astro looks for `.astro` or `.md` files in the `src/pages/` directory. Each page is exposed as a route based on its file name.

There's nothing special about `src/components/`, but that's where we like to put any Astro/React/Vue/Svelte/Preact components.

Any static assets, like images, can be placed in the `public/` directory.

=== Commands

All commands are run from the root of the project, from a terminal:

|===
| Command | Action

| `pnpm install`
| Installs dependencies

| `pnpm run dev`
| Starts local dev server at `localhost:4321`

| `pnpm run build`
| Build your production site to `./dist/`

| `pnpm run preview`
| Preview your build locally, before deploying

| `p+npm run astro ...+`
| Run CLI commands like `astro add`, `astro check`

| `+pnpm run astro -- --help+`
| Get help using the Astro CLI
|===

=== Deployment

Push all changes to the `staging` branch,
and changes will be automatically deployed and reflected on the staging site.
