name: build

on:
  push:
    branches:
      - '*'         # matches every branch
      - '*/*'       # matches every branch containing a single '/'
      - '!master'   # excludes master
      - '!staging'   # excludes master

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev libicu-dev zlib1g-dev openssl
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Setup snaps
        run: |
          sudo snap install yq
          sudo snap install aws-cli --classic
          sudo snap install node --classic --channel=10/stable
      - name: Setup Metanorma locally
        run: |
          curl -L https://raw.githubusercontent.com/metanorma/metanorma-linux-setup/master/ubuntu.sh | sudo bash
      - name: Setup git submodules
        # env:
        #   MLGT_DATA_DEPLOY_KEY: ${{ secrets.MLGT_DATA_DEPLOY_KEY }}
        #   GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          # eval "$(ssh-agent -s)"
          # ssh-add - <<< "${MLGT_DATA_DEPLOY_KEY}"
          make update-init update-modules
      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          bundle install --jobs 4 --retry 3
      # - name: Build document in the Metanorma container
      #   env:
      #     METANORMA_DOCKER: metanorma/mn:latest
      - name: Build site
        env:
          JAVA_OPTS: "java.awt.headless=true"
        run: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm --version
          make _site
